services:
  web:
    build: .
    container_name: sistema_uacm_web
    command: >
      bash -c " ./wait-for-it.sh db:3306 --timeout=120 --strict -- && python manage.py migrate && python manage.py runserver 0.0.0.0:8000 "
    volumes:
      - .:/app
      - ./frontend_uacm/build:/app/frontend_uacm/build
      - ./staticfiles:/app/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - default

  db:
    image: mysql:8.0
    container_name: sistema_uacm_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: uacm_db
      MYSQL_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - default

volumes:
  db_data:
  staticfiles:


networks:
  default:
    driver: bridge
