-- MySQL Script generated by MySQL Workbench
-- Sat Apr 11 18:48:54 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema uacm_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema uacm_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `uacm_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `uacm_db` ;

-- -----------------------------------------------------
-- Table `uacm_db`.`estado_almacen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uacm_db`.`estado_almacen` (
  `id_estado_almacen` INT NOT NULL AUTO_INCREMENT,
  `nombre_estado_almacen` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_estado_almacen`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `uacm_db`.`categoria_salarial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uacm_db`.`categoria_salarial` (
  `id_cat_sal` INT NOT NULL AUTO_INCREMENT,
  `categoria_salarial` VARCHAR(50) NOT NULL,
  `descripcion` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id_cat_sal`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `uacm_db`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uacm_db`.`rol` (
  `id_rol` INT NOT NULL AUTO_INCREMENT,
  `nombre_rol` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id_rol`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `uacm_db`.`personal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uacm_db`.`personal` (
  `id_personal` INT NOT NULL,
  `nombre_personal` VARCHAR(50) NOT NULL,
  `apellido_paterno` VARCHAR(50) NOT NULL,
  `apellido_materno` VARCHAR(50) NULL DEFAULT NULL,
  `telefono` VARCHAR(10) NOT NULL,
  `correo` VARCHAR(250) NOT NULL,
  `id_categoria_sal` INT NULL DEFAULT NULL,
  `id_rol` INT NOT NULL,
  PRIMARY KEY (`id_personal`),
  INDEX `personal_id_categoria_sal_76756278_fk_categoria` (`id_categoria_sal` ASC) VISIBLE,
  INDEX `personal_id_rol_ce5f7404_fk_rol_id_rol` (`id_rol` ASC) VISIBLE,
  CONSTRAINT `personal_id_categoria_sal_76756278_fk_categoria`
    FOREIGN KEY (`id_categoria_sal`)
    REFERENCES `uacm_db`.`categoria_salarial` (`id_cat_sal`),
  CONSTRAINT `personal_id_rol_ce5f7404_fk_rol_id_rol`
    FOREIGN KEY (`id_rol`)
    REFERENCES `uacm_db`.`rol` (`id_rol`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `uacm_db`.`tipo_almacen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uacm_db`.`tipo_almacen` (
  `id_talmacen` INT NOT NULL AUTO_INCREMENT,
  `tipo_almacen` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_talmacen`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `uacm_db`.`almacen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uacm_db`.`almacen` (
  `id_almacen` INT NOT NULL AUTO_INCREMENT,
  `direccion` VARCHAR(250) NOT NULL,
  `correo` VARCHAR(250) NULL DEFAULT NULL,
  `telefono` VARCHAR(10) NULL DEFAULT NULL,
  `capacidad_maxima` INT NOT NULL,
  `id_estado_almacen` INT NOT NULL,
  `id_responsable` INT NULL DEFAULT NULL,
  `id_talmacen` INT NOT NULL,
  PRIMARY KEY (`id_almacen`),
  UNIQUE INDEX `id_responsable` (`id_responsable` ASC) VISIBLE,
  INDEX `almacen_id_estado_almacen_2d31bc1a_fk_estado_al` (`id_estado_almacen` ASC) VISIBLE,
  INDEX `almacen_id_talmacen_6e4a3742_fk_tipo_almacen_id_talmacen` (`id_talmacen` ASC) VISIBLE,
  CONSTRAINT `almacen_id_estado_almacen_2d31bc1a_fk_estado_al`
    FOREIGN KEY (`id_estado_almacen`)
    REFERENCES `uacm_db`.`estado_almacen` (`id_estado_almacen`),
  CONSTRAINT `almacen_id_responsable_4a7303bd_fk_personal_id_personal`
    FOREIGN KEY (`id_responsable`)
    REFERENCES `uacm_db`.`personal` (`id_personal`),
  CONSTRAINT `almacen_id_talmacen_6e4a3742_fk_tipo_almacen_id_talmacen`
    FOREIGN KEY (`id_talmacen`)
    REFERENCES `uacm_db`.`tipo_almacen` (`id_talmacen`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `uacm_db`.`auth_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uacm_db`.`auth_group` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `uacm_db`.`django_content_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uacm_db`.`django_content_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `app_label` VARCHAR(100) NOT NULL,
  `model` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `django_content_type_app_label_model_76bd3d3b_uniq` (`app_label` ASC, `model` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 23
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `uacm_db`.`auth_permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uacm_db`.`auth_permission` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `content_type_id` INT NOT NULL,
  `codename` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `auth_permission_content_type_id_codename_01ab375a_uniq` (`content_type_id` ASC, `codename` ASC) VISIBLE,
  CONSTRAINT `auth_permission_content_type_id_2f476e4b_fk_django_co`
    FOREIGN KEY (`content_type_id`)
    REFERENCES `uacm_db`.`django_content_type` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 89
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `uacm_db`.`auth_group_permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uacm_db`.`auth_group_permissions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `group_id` INT NOT NULL,
  `permission_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `auth_group_permissions_group_id_permission_id_0cd325b0_uniq` (`group_id` ASC, `permission_id` ASC) VISIBLE,
  INDEX `auth_group_permissio_permission_id_84c5c92e_fk_auth_perm` (`permission_id` ASC) VISIBLE,
  CONSTRAINT `auth_group_permissio_permission_id_84c5c92e_fk_auth_perm`
    FOREIGN KEY (`permission_id`)
    REFERENCES `uacm_db`.`auth_permission` (`id`),
  CONSTRAINT `auth_group_permissions_group_id_b120cbf9_fk_auth_group_id`
    FOREIGN KEY (`group_id`)
    REFERENCES `uacm_db`.`auth_group` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `uacm_db`.`auth_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uacm_db`.`auth_user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `password` VARCHAR(128) NOT NULL,
  `last_login` DATETIME(6) NULL DEFAULT NULL,
  `is_superuser` TINYINT(1) NOT NULL,
  `username` VARCHAR(150) NOT NULL,
  `first_name` VARCHAR(150) NOT NULL,
  `last_name` VARCHAR(150) NOT NULL,
  `email` VARCHAR(254) NOT NULL,
  `is_staff` TINYINT(1) NOT NULL,
  `is_active` TINYINT(1) NOT NULL,
  `date_joined` DATETIME(6) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username` (`username` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `uacm_db`.`auth_user_groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uacm_db`.`auth_user_groups` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `group_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `auth_user_groups_user_id_group_id_94350c0c_uniq` (`user_id` ASC, `group_id` ASC) VISIBLE,
  INDEX `auth_user_groups_group_id_97559544_fk_auth_group_id` (`group_id` ASC) VISIBLE,
  CONSTRAINT `auth_user_groups_group_id_97559544_fk_auth_group_id`
    FOREIGN KEY (`group_id`)
    REFERENCES `uacm_db`.`auth_group` (`id`),
  CONSTRAINT `auth_user_groups_user_id_6a12ed8b_fk_auth_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `uacm_db`.`auth_user` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `uacm_db`.`auth_user_user_permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uacm_db`.`auth_user_user_permissions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `permission_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `auth_user_user_permissions_user_id_permission_id_14a6b632_uniq` (`user_id` ASC, `permission_id` ASC) VISIBLE,
  INDEX `auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm` (`permission_id` ASC) VISIBLE,
  CONSTRAINT `auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm`
    FOREIGN KEY (`permission_id`)
    REFERENCES `uacm_db`.`auth_permission` (`id`),
  CONSTRAINT `auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `uacm_db`.`auth_user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `uacm_db`.`estatus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uacm_db`.`estatus` (
  `id_estatus` INT NOT NULL AUTO_INCREMENT,
  `nombre_estatus` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_estatus`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `uacm_db`.`categoria_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uacm_db`.`categoria_producto` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `nombre_categoria` VARCHAR(100) NOT NULL,
  `descripcion_categoria` VARCHAR(300) NOT NULL,
  `fecha_creacion` DATETIME(6) NOT NULL,
  `id_estatus` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_categoria`),
  INDEX `categoria_producto_id_estatus_77b76446_fk_estatus_id_estatus` (`id_estatus` ASC) VISIBLE,
  CONSTRAINT `categoria_producto_id_estatus_77b76446_fk_estatus_id_estatus`
    FOREIGN KEY (`id_estatus`)
    REFERENCES `uacm_db`.`estatus` (`id_estatus`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `uacm_db`.`marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uacm_db`.`marca` (
  `id_marca` INT NOT NULL AUTO_INCREMENT,
  `nombre_marca` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_marca`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `uacm_db`.`unidad_medida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uacm_db`.`unidad_medida` (
  `id_unidad` INT NOT NULL AUTO_INCREMENT,
  `nombre_unidad` VARCHAR(50) NOT NULL,
  `abreviatura` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`id_unidad`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `uacm_db`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uacm_db`.`producto` (
  `id_producto` INT NOT NULL AUTO_INCREMENT,
  `nombre_producto` VARCHAR(100) NOT NULL,
  `descripcion_producto` VARCHAR(300) NULL DEFAULT NULL,
  `cantidad` INT NOT NULL,
  `stock_minimo` INT NOT NULL,
  `observaciones` VARCHAR(300) NULL DEFAULT NULL,
  `fecha_creacion` DATETIME(6) NOT NULL,
  `imagen_producto` VARCHAR(250) NULL DEFAULT NULL,
  `id_categoria` INT NULL DEFAULT NULL,
  `id_estatus` INT NULL DEFAULT NULL,
  `id_marca` INT NULL DEFAULT NULL,
  `id_unidad` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_producto`),
  INDEX `producto_id_categoria_710ea567_fk_categoria` (`id_categoria` ASC) VISIBLE,
  INDEX `producto_id_estatus_05277fba_fk_estatus_id_estatus` (`id_estatus` ASC) VISIBLE,
  INDEX `producto_id_marca_1c10233d_fk_marca_id_marca` (`id_marca` ASC) VISIBLE,
  INDEX `producto_id_unidad_3a3a2924_fk_unidad_medida_id_unidad` (`id_unidad` ASC) VISIBLE,
  CONSTRAINT `producto_id_categoria_710ea567_fk_categoria`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `uacm_db`.`categoria_producto` (`id_categoria`),
  CONSTRAINT `producto_id_estatus_05277fba_fk_estatus_id_estatus`
    FOREIGN KEY (`id_estatus`)
    REFERENCES `uacm_db`.`estatus` (`id_estatus`),
  CONSTRAINT `producto_id_marca_1c10233d_fk_marca_id_marca`
    FOREIGN KEY (`id_marca`)
    REFERENCES `uacm_db`.`marca` (`id_marca`),
  CONSTRAINT `producto_id_unidad_3a3a2924_fk_unidad_medida_id_unidad`
    FOREIGN KEY (`id_unidad`)
    REFERENCES `uacm_db`.`unidad_medida` (`id_unidad`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `uacm_db`.`estatus_solicitud`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uacm_db`.`estatus_solicitud` (
  `id_estatus_solicitud` INT NOT NULL AUTO_INCREMENT,
  `nombre_estatus` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_estatus_solicitud`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `uacm_db`.`solicitud`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uacm_db`.`solicitud` (
  `id_solicitud` INT NOT NULL AUTO_INCREMENT,
  `fecha_solicitud` DATETIME(6) NOT NULL,
  `observaciones_solicitud` VARCHAR(300) NULL DEFAULT NULL,
  `id_almacen` INT NULL DEFAULT NULL,
  `id_estatus` INT NULL DEFAULT NULL,
  `id_personal` INT NULL DEFAULT NULL,
  `gestionado_por` INT NULL DEFAULT NULL,
  `fecha_gestion` DATETIME(6) NULL DEFAULT NULL,
  `id_solicitud_origen` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_solicitud`),
  INDEX `solicitud_id_almacen_6634a6e2_fk_almacen_id_almacen` (`id_almacen` ASC) VISIBLE,
  INDEX `solicitud_id_estatus_87649ec7_fk_estatus_s` (`id_estatus` ASC) VISIBLE,
  INDEX `solicitud_id_personal_7a67532c_fk_personal_id_personal` (`id_personal` ASC) VISIBLE,
  INDEX `solicitud_aprobado_por_3c1e85a7` (`gestionado_por` ASC) VISIBLE,
  INDEX `solicitud_id_solicitud_origen_8166b0f0_fk_solicitud_id_solicitud` (`id_solicitud_origen` ASC) VISIBLE,
  CONSTRAINT `solicitud_aprobado_por_3c1e85a7_fk_personal_id_personal`
    FOREIGN KEY (`gestionado_por`)
    REFERENCES `uacm_db`.`personal` (`id_personal`),
  CONSTRAINT `solicitud_id_almacen_6634a6e2_fk_almacen_id_almacen`
    FOREIGN KEY (`id_almacen`)
    REFERENCES `uacm_db`.`almacen` (`id_almacen`),
  CONSTRAINT `solicitud_id_estatus_87649ec7_fk_estatus_s`
    FOREIGN KEY (`id_estatus`)
    REFERENCES `uacm_db`.`estatus_solicitud` (`id_estatus_solicitud`),
  CONSTRAINT `solicitud_id_personal_7a67532c_fk_personal_id_personal`
    FOREIGN KEY (`id_personal`)
    REFERENCES `uacm_db`.`personal` (`id_personal`),
  CONSTRAINT `solicitud_id_solicitud_origen_8166b0f0_fk_solicitud_id_solicitud`
    FOREIGN KEY (`id_solicitud_origen`)
    REFERENCES `uacm_db`.`solicitud` (`id_solicitud`))
ENGINE = InnoDB
AUTO_INCREMENT = 58
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `uacm_db`.`detalle_solicitud`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uacm_db`.`detalle_solicitud` (
  `id_detalle` INT NOT NULL AUTO_INCREMENT,
  `cantidad` INT NOT NULL,
  `id_producto` INT NOT NULL,
  `id_solicitud` INT NOT NULL,
  `cantidad_recibida` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_detalle`),
  UNIQUE INDEX `detalle_solicitud_id_solicitud_id_producto_347ebe57_uniq` (`id_solicitud` ASC, `id_producto` ASC) VISIBLE,
  INDEX `detalle_solicitud_id_producto_e5b7efeb_fk_producto_id_producto` (`id_producto` ASC) VISIBLE,
  CONSTRAINT `detalle_solicitud_id_producto_e5b7efeb_fk_producto_id_producto`
    FOREIGN KEY (`id_producto`)
    REFERENCES `uacm_db`.`producto` (`id_producto`),
  CONSTRAINT `detalle_solicitud_id_solicitud_cd90d05a_fk_solicitud`
    FOREIGN KEY (`id_solicitud`)
    REFERENCES `uacm_db`.`solicitud` (`id_solicitud`))
ENGINE = InnoDB
AUTO_INCREMENT = 80
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `uacm_db`.`django_admin_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uacm_db`.`django_admin_log` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `action_time` DATETIME(6) NOT NULL,
  `object_id` LONGTEXT NULL DEFAULT NULL,
  `object_repr` VARCHAR(200) NOT NULL,
  `action_flag` SMALLINT UNSIGNED NOT NULL,
  `change_message` LONGTEXT NOT NULL,
  `content_type_id` INT NULL DEFAULT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `django_admin_log_content_type_id_c4bce8eb_fk_django_co` (`content_type_id` ASC) VISIBLE,
  INDEX `django_admin_log_user_id_c564eba6_fk_auth_user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `django_admin_log_content_type_id_c4bce8eb_fk_django_co`
    FOREIGN KEY (`content_type_id`)
    REFERENCES `uacm_db`.`django_content_type` (`id`),
  CONSTRAINT `django_admin_log_user_id_c564eba6_fk_auth_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `uacm_db`.`auth_user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `uacm_db`.`django_migrations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uacm_db`.`django_migrations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `app` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `applied` DATETIME(6) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 31
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `uacm_db`.`django_session`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uacm_db`.`django_session` (
  `session_key` VARCHAR(40) NOT NULL,
  `session_data` LONGTEXT NOT NULL,
  `expire_date` DATETIME(6) NOT NULL,
  PRIMARY KEY (`session_key`),
  INDEX `django_session_expire_date_a5c62663` (`expire_date` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `uacm_db`.`limite_solicitud`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uacm_db`.`limite_solicitud` (
  `id_limite` INT NOT NULL AUTO_INCREMENT,
  `id_producto` INT NOT NULL,
  `cantidad_maxima` INT NOT NULL DEFAULT '5',
  `periodo` ENUM('diario', 'semanal', 'mensual') NOT NULL DEFAULT 'diario',
  PRIMARY KEY (`id_limite`),
  INDEX `fk_limite_producto` (`id_producto` ASC) VISIBLE,
  CONSTRAINT `fk_limite_producto`
    FOREIGN KEY (`id_producto`)
    REFERENCES `uacm_db`.`producto` (`id_producto`))
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `uacm_db`.`perfil_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uacm_db`.`perfil_usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_personal` INT NULL DEFAULT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `perfil_usuario_user_id_a77a2a33_fk_auth_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `uacm_db`.`auth_user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

USE `uacm_db` ;

-- -----------------------------------------------------
-- procedure sp_aprobar_solicitud
-- -----------------------------------------------------

DELIMITER $$
USE `uacm_db`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_aprobar_solicitud`(IN p_id_solicitud INT)
BEGIN
    DECLARE v_estatus      INT DEFAULT NULL;
    DECLARE v_id_solicitada INT;
    DECLARE v_id_aprobada  INT;

    DECLARE CONTINUE HANDLER FOR NOT FOUND SET v_estatus = NULL;

    SELECT id_estatus_solicitud INTO v_id_solicitada
    FROM estatus_solicitud WHERE nombre_estatus = 'SOLICITADA' LIMIT 1;

    SELECT id_estatus_solicitud INTO v_id_aprobada
    FROM estatus_solicitud WHERE nombre_estatus = 'APROBADA' LIMIT 1;

    SELECT id_estatus INTO v_estatus
    FROM solicitud WHERE id_solicitud = p_id_solicitud;

    IF v_estatus IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Solicitud no encontrada';
    END IF;

    IF v_estatus != v_id_solicitada THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Solo se pueden aprobar solicitudes en estado Solicitada';
    END IF;

    UPDATE solicitud SET id_estatus = v_id_aprobada WHERE id_solicitud = p_id_solicitud;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_cabecera_solicitud
-- -----------------------------------------------------

DELIMITER $$
USE `uacm_db`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_cabecera_solicitud`(IN p_id_solicitud INT)
BEGIN
    SELECT
        s.id_solicitud,
        a.id_almacen,
        ta.tipo_almacen,
        s.fecha_solicitud,
        p.id_personal,
        CONCAT(p.nombre_personal, ' ', p.apellido_paterno,
               IFNULL(CONCAT(' ', p.apellido_materno), '')) AS nombre,
        p.id_rol,
        r.nombre_rol,
        es.nombre_estatus,
        s.observaciones_solicitud
    FROM solicitud s
    JOIN almacen a              ON a.id_almacen            = s.id_almacen
    JOIN tipo_almacen ta        ON ta.id_talmacen          = a.id_talmacen
    JOIN estatus_solicitud es   ON es.id_estatus_solicitud = s.id_estatus
    LEFT JOIN personal p        ON p.id_personal           = s.id_personal
    LEFT JOIN rol r             ON r.id_rol                = p.id_rol
    WHERE s.id_solicitud = p_id_solicitud;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_cancelar_solicitud
-- -----------------------------------------------------

DELIMITER $$
USE `uacm_db`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_cancelar_solicitud`(IN p_id_solicitud INT)
BEGIN
    DECLARE v_estatus        INT DEFAULT NULL;
    DECLARE v_id_solicitada  INT;
    DECLARE v_id_cancelada   INT;
    DECLARE v_id_prod_inact  INT;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        RESIGNAL;
    END;

    SELECT id_estatus_solicitud INTO v_id_solicitada
    FROM estatus_solicitud WHERE nombre_estatus = 'SOLICITADA' LIMIT 1;

    SELECT id_estatus_solicitud INTO v_id_cancelada
    FROM estatus_solicitud WHERE nombre_estatus = 'CANCELADA' LIMIT 1;

    SELECT id_estatus INTO v_id_prod_inact
    FROM estatus WHERE nombre_estatus = 'Inactivo' LIMIT 1;

    SELECT id_estatus INTO v_estatus
    FROM solicitud WHERE id_solicitud = p_id_solicitud;

    IF v_estatus IS NULL THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Solicitud no encontrada';
    END IF;

    IF v_estatus != v_id_solicitada THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'La solicitud no puede cancelarse';
    END IF;

    START TRANSACTION;

    UPDATE producto p
    JOIN detalle_solicitud d ON p.id_producto = d.id_producto
    SET p.cantidad = p.cantidad + d.cantidad
    WHERE d.id_solicitud = p_id_solicitud
      AND p.id_estatus != v_id_prod_inact;

    UPDATE solicitud SET id_estatus = v_id_cancelada WHERE id_solicitud = p_id_solicitud;

    COMMIT;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_crear_solicitud
-- -----------------------------------------------------

DELIMITER $$
USE `uacm_db`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_crear_solicitud`(
    IN p_id_almacen    INT,
    IN p_id_personal   INT,
    IN p_observaciones VARCHAR(300),
    IN p_productos     JSON
)
BEGIN
    DECLARE v_id_solicitud    INT;
    DECLARE v_index           INT DEFAULT 0;
    DECLARE v_total           INT DEFAULT 0;
    DECLARE v_id_producto     INT;
    DECLARE v_cantidad        INT;
    DECLARE v_stock           INT;
    DECLARE v_estatus_prod    INT;
    DECLARE v_id_est_sol      INT;
    DECLARE v_id_prod_inact   INT;
    DECLARE v_id_prod_activo  INT;
    DECLARE v_id_prod_agotado INT;
    DECLARE v_es_central      INT DEFAULT 0;
    DECLARE v_id_tipo_central INT;
    DECLARE v_id_cancelada    INT;
    DECLARE v_limite_max      INT DEFAULT NULL;
    DECLARE v_periodo_lim     VARCHAR(10) DEFAULT NULL;
    DECLARE v_ya_solicitado   INT DEFAULT 0;
    DECLARE v_nombre_prod     VARCHAR(255);
    DECLARE v_msg             VARCHAR(500);

    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        RESIGNAL;
    END;

    SELECT id_estatus_solicitud INTO v_id_est_sol
    FROM estatus_solicitud WHERE nombre_estatus = 'SOLICITADA' LIMIT 1;

    SELECT id_estatus_solicitud INTO v_id_cancelada
    FROM estatus_solicitud WHERE nombre_estatus = 'CANCELADA' LIMIT 1;

    SELECT id_estatus INTO v_id_prod_inact
    FROM estatus WHERE nombre_estatus = 'Inactivo' LIMIT 1;

    SELECT id_estatus INTO v_id_prod_activo
    FROM estatus WHERE nombre_estatus = 'Activo' LIMIT 1;

    SELECT id_estatus INTO v_id_prod_agotado
    FROM estatus WHERE nombre_estatus = 'Agotado' LIMIT 1;

    SELECT id_talmacen INTO v_id_tipo_central
    FROM tipo_almacen WHERE LOWER(tipo_almacen) LIKE '%central%' LIMIT 1;

    SELECT COUNT(*) INTO v_es_central
    FROM almacen
    WHERE id_almacen = p_id_almacen
      AND id_talmacen = v_id_tipo_central;

    START TRANSACTION;

    INSERT INTO solicitud (id_almacen, id_personal, observaciones_solicitud, id_estatus, fecha_solicitud)
    VALUES (p_id_almacen, p_id_personal, p_observaciones, v_id_est_sol, NOW());

    SET v_id_solicitud = LAST_INSERT_ID();
    SET v_total = IFNULL(JSON_LENGTH(p_productos), 0);

    WHILE v_index < v_total DO
        SET v_id_producto = CAST(JSON_UNQUOTE(JSON_EXTRACT(p_productos, CONCAT('$[', v_index, '].id_producto'))) AS UNSIGNED);
        SET v_cantidad    = CAST(JSON_UNQUOTE(JSON_EXTRACT(p_productos, CONCAT('$[', v_index, '].cantidad')))    AS UNSIGNED);

        SELECT cantidad, id_estatus, nombre_producto
        INTO v_stock, v_estatus_prod, v_nombre_prod
        FROM producto
        WHERE id_producto = v_id_producto
        FOR UPDATE;

        IF v_estatus_prod != v_id_prod_inact AND v_es_central = 0 THEN

            SET v_limite_max  = NULL;
            SET v_periodo_lim = NULL;

            SELECT cantidad_maxima, periodo
            INTO v_limite_max, v_periodo_lim
            FROM limite_solicitud
            WHERE id_producto = v_id_producto
            LIMIT 1;

            IF v_limite_max IS NOT NULL AND p_id_personal IS NOT NULL THEN
                SELECT COALESCE(SUM(ds.cantidad), 0) INTO v_ya_solicitado
                FROM detalle_solicitud ds
                JOIN solicitud s ON s.id_solicitud = ds.id_solicitud
                JOIN almacen a ON a.id_almacen = s.id_almacen
                WHERE s.id_personal = p_id_personal
                  AND ds.id_producto = v_id_producto
                  AND s.id_estatus != v_id_cancelada
                  AND a.id_talmacen != v_id_tipo_central
                  AND CASE v_periodo_lim
                        WHEN 'diario'  THEN DATE(s.fecha_solicitud) = CURDATE()
                        WHEN 'semanal' THEN YEARWEEK(s.fecha_solicitud, 1) = YEARWEEK(NOW(), 1)
                        WHEN 'mensual' THEN YEAR(s.fecha_solicitud) = YEAR(NOW())
                                        AND MONTH(s.fecha_solicitud) = MONTH(NOW())
                      END;

                IF (v_ya_solicitado + v_cantidad) > v_limite_max THEN
                    SET v_msg = CONCAT('Limite superado para "', v_nombre_prod,
                        '": maximo ', v_limite_max,
                        ' unidades por periodo. Ya solicitadas: ', v_ya_solicitado);
                    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = v_msg;
                END IF;
            END IF;

            IF v_stock < v_cantidad THEN
                SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Stock insuficiente';
            END IF;

            UPDATE producto SET cantidad = cantidad - v_cantidad WHERE id_producto = v_id_producto;

            UPDATE producto
            SET id_estatus = v_id_prod_agotado
            WHERE id_producto = v_id_producto
              AND cantidad = 0
              AND id_estatus = v_id_prod_activo;
        END IF;

        INSERT INTO detalle_solicitud (id_solicitud, id_producto, cantidad)
        VALUES (v_id_solicitud, v_id_producto, v_cantidad);

        SET v_index = v_index + 1;
    END WHILE;

    COMMIT;

    SELECT v_id_solicitud AS id_solicitud;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_datos_gestion
-- -----------------------------------------------------

DELIMITER $$
USE `uacm_db`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_datos_gestion`(
    IN p_id_solicitud INT
)
BEGIN
    SELECT s.fecha_gestion,
           p.id_personal, p.nombre_personal, p.apellido_paterno, p.apellido_materno,
           r.nombre_rol
    FROM solicitud s
    LEFT JOIN personal p ON p.id_personal = s.gestionado_por
    LEFT JOIN rol r ON r.id_rol = p.id_rol
    WHERE s.id_solicitud = p_id_solicitud;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_detalle_solicitud
-- -----------------------------------------------------

DELIMITER $$
USE `uacm_db`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_detalle_solicitud`(IN p_id_solicitud INT)
BEGIN
    SELECT
        s.id_solicitud,
        a.id_almacen,
        ta.tipo_almacen,
        s.fecha_solicitud,
        p.id_personal,
        CONCAT(p.nombre_personal, ' ', p.apellido_paterno,
               IFNULL(CONCAT(' ', p.apellido_materno), '')) AS nombre,
        p.id_rol,
        r.nombre_rol,
        es.nombre_estatus,
        s.observaciones_solicitud
    FROM solicitud s
    JOIN almacen a              ON a.id_almacen            = s.id_almacen
    JOIN tipo_almacen ta        ON ta.id_talmacen          = a.id_talmacen
    JOIN estatus_solicitud es   ON es.id_estatus_solicitud = s.id_estatus
    LEFT JOIN personal p        ON p.id_personal           = s.id_personal
    LEFT JOIN rol r             ON r.id_rol                = p.id_rol
    WHERE s.id_solicitud = p_id_solicitud;

    SELECT
        pr.id_producto,
        pr.nombre_producto,
        d.cantidad
    FROM detalle_solicitud d
    JOIN producto pr ON pr.id_producto = d.id_producto
    WHERE d.id_solicitud = p_id_solicitud;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_productos_solicitud
-- -----------------------------------------------------

DELIMITER $$
USE `uacm_db`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_productos_solicitud`(IN p_id_solicitud INT)
BEGIN
    SELECT
        pr.id_producto,
        pr.nombre_producto,
        d.cantidad,
        d.cantidad_recibida
    FROM detalle_solicitud d
    JOIN producto pr ON pr.id_producto = d.id_producto
    WHERE d.id_solicitud = p_id_solicitud;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_registrar_gestion
-- -----------------------------------------------------

DELIMITER $$
USE `uacm_db`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_registrar_gestion`(
    IN p_id_solicitud INT,
    IN p_id_personal INT
)
BEGIN
    UPDATE solicitud
    SET gestionado_por = p_id_personal,
        fecha_gestion  = NOW()
    WHERE id_solicitud = p_id_solicitud;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_registrar_recepcion
-- -----------------------------------------------------

DELIMITER $$
USE `uacm_db`$$
CREATE DEFINER=`root`@`%` PROCEDURE `sp_registrar_recepcion`(
    IN p_id_solicitud INT,
    IN p_productos    JSON
)
BEGIN
    DECLARE v_index           INT DEFAULT 0;
    DECLARE v_total           INT DEFAULT 0;
    DECLARE v_id_producto     INT;
    DECLARE v_cant_rec        INT;
    DECLARE v_cant_sol        INT;
    DECLARE v_faltante        INT;
    DECLARE v_hay_parcial     INT DEFAULT 0;
    DECLARE v_id_parcial      INT;
    DECLARE v_id_completada   INT;
    DECLARE v_id_solicitada   INT;
    DECLARE v_id_almacen      INT;
    DECLARE v_id_personal     INT;
    DECLARE v_id_nueva_sol    INT DEFAULT 0;
    DECLARE v_es_central      INT DEFAULT 0;
    DECLARE v_id_tipo_central INT;
    DECLARE v_id_est_activo   INT;
    DECLARE v_id_est_agotado  INT;

    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Error al registrar la recepción';
    END;

    SELECT id_estatus_solicitud INTO v_id_parcial    FROM estatus_solicitud WHERE nombre_estatus = 'ENTREGA_PARCIAL' LIMIT 1;
    SELECT id_estatus_solicitud INTO v_id_completada FROM estatus_solicitud WHERE nombre_estatus = 'COMPLETADA'      LIMIT 1;
    SELECT id_estatus_solicitud INTO v_id_solicitada FROM estatus_solicitud WHERE nombre_estatus = 'SOLICITADA'      LIMIT 1;
    SELECT id_talmacen INTO v_id_tipo_central FROM tipo_almacen WHERE LOWER(tipo_almacen) LIKE '%central%' LIMIT 1;
    SELECT id_estatus INTO v_id_est_activo  FROM estatus WHERE nombre_estatus = 'Activo'  LIMIT 1;
    SELECT id_estatus INTO v_id_est_agotado FROM estatus WHERE nombre_estatus = 'Agotado' LIMIT 1;

    SELECT id_almacen, id_personal INTO v_id_almacen, v_id_personal
    FROM solicitud WHERE id_solicitud = p_id_solicitud;

    SELECT COUNT(*) INTO v_es_central FROM almacen
    WHERE id_almacen = v_id_almacen AND id_talmacen = v_id_tipo_central;

    START TRANSACTION;

    SET v_total = JSON_LENGTH(p_productos);

    WHILE v_index < v_total DO
        SET v_id_producto = JSON_UNQUOTE(JSON_EXTRACT(p_productos, CONCAT('$[', v_index, '].id_producto')));
        SET v_cant_rec    = JSON_UNQUOTE(JSON_EXTRACT(p_productos, CONCAT('$[', v_index, '].cantidad_recibida')));

        UPDATE detalle_solicitud SET cantidad_recibida = v_cant_rec
        WHERE id_solicitud = p_id_solicitud AND id_producto = v_id_producto;

        SELECT cantidad INTO v_cant_sol FROM detalle_solicitud
        WHERE id_solicitud = p_id_solicitud AND id_producto = v_id_producto;

        IF v_es_central = 1 AND v_cant_rec > 0 THEN
            UPDATE producto SET cantidad = cantidad + v_cant_rec WHERE id_producto = v_id_producto;
            UPDATE producto SET id_estatus = v_id_est_activo
            WHERE id_producto = v_id_producto AND id_estatus = v_id_est_agotado;
        END IF;

        IF v_cant_sol > v_cant_rec THEN SET v_hay_parcial = 1; END IF;
        SET v_index = v_index + 1;
    END WHILE;

    IF v_hay_parcial = 1 THEN
        UPDATE solicitud SET id_estatus = v_id_parcial WHERE id_solicitud = p_id_solicitud;

        INSERT INTO solicitud (id_almacen, id_personal, observaciones_solicitud, id_estatus, fecha_solicitud, id_solicitud_origen)
        VALUES (v_id_almacen, v_id_personal,
                CONCAT('Seguimiento de solicitud #', p_id_solicitud, ' — entrega parcial'),
                v_id_solicitada, NOW(), p_id_solicitud);

        SET v_id_nueva_sol = LAST_INSERT_ID();
        SET v_index = 0;

        WHILE v_index < v_total DO
            SET v_id_producto = JSON_UNQUOTE(JSON_EXTRACT(p_productos, CONCAT('$[', v_index, '].id_producto')));
            SET v_cant_rec    = JSON_UNQUOTE(JSON_EXTRACT(p_productos, CONCAT('$[', v_index, '].cantidad_recibida')));
            SELECT cantidad INTO v_cant_sol FROM detalle_solicitud
            WHERE id_solicitud = p_id_solicitud AND id_producto = v_id_producto;
            SET v_faltante = v_cant_sol - v_cant_rec;
            IF v_faltante > 0 THEN
                INSERT INTO detalle_solicitud (id_solicitud, id_producto, cantidad)
                VALUES (v_id_nueva_sol, v_id_producto, v_faltante);
            END IF;
            SET v_index = v_index + 1;
        END WHILE;
    ELSE
        UPDATE solicitud SET id_estatus = v_id_completada WHERE id_solicitud = p_id_solicitud;
    END IF;

    COMMIT;
    SELECT v_id_nueva_sol AS id_solicitud_nueva;
END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
