-- MySQL Script generated by MySQL Workbench
-- Mon Mar 16 18:15:19 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema uacm_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema uacm_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `uacm_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `uacm_db` ;

-- -----------------------------------------------------
-- Table `uacm_db`.`tipo_almacen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uacm_db`.`tipo_almacen` (
  `id_talmacen` INT NOT NULL AUTO_INCREMENT,
  `tipo_almacen` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_talmacen`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `uacm_db`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uacm_db`.`rol` (
  `id_rol` INT NOT NULL AUTO_INCREMENT,
  `nombre_rol` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id_rol`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `uacm_db`.`categoria_salarial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uacm_db`.`categoria_salarial` (
  `id_cat_sal` INT NOT NULL AUTO_INCREMENT,
  `categoria_salarial` VARCHAR(50) NOT NULL,
  `descripcion` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id_cat_sal`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `uacm_db`.`personal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uacm_db`.`personal` (
  `id_personal` INT NOT NULL,
  `id_rol` INT NULL DEFAULT NULL,
  `nombre_personal` VARCHAR(50) NOT NULL,
  `apellido_paterno` VARCHAR(50) NOT NULL,
  `apellido_materno` VARCHAR(50) NULL DEFAULT NULL,
  `telefono` VARCHAR(10) NOT NULL,
  `correo` VARCHAR(250) NOT NULL,
  `id_categoria_sal` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_personal`),
  INDEX `id_rol` (`id_rol` ASC) VISIBLE,
  INDEX `id_categoria_sal` (`id_categoria_sal` ASC) VISIBLE,
  CONSTRAINT `personal_ibfk_1`
    FOREIGN KEY (`id_rol`)
    REFERENCES `uacm_db`.`rol` (`id_rol`),
  CONSTRAINT `personal_ibfk_2`
    FOREIGN KEY (`id_categoria_sal`)
    REFERENCES `uacm_db`.`categoria_salarial` (`id_cat_sal`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `uacm_db`.`estado_almacen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uacm_db`.`estado_almacen` (
  `id_estado_almacen` INT NOT NULL AUTO_INCREMENT,
  `nombre_estado_almacen` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_estado_almacen`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `uacm_db`.`almacen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uacm_db`.`almacen` (
  `id_almacen` INT NOT NULL AUTO_INCREMENT,
  `id_talmacen` INT NULL DEFAULT NULL,
  `direccion` VARCHAR(250) NOT NULL,
  `correo` VARCHAR(250) NULL DEFAULT NULL,
  `telefono` VARCHAR(10) NULL DEFAULT NULL,
  `capacidad_maxima` INT NOT NULL,
  `id_estado_almacen` INT NULL DEFAULT NULL,
  `id_responsable` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_almacen`),
  UNIQUE INDEX `id_responsable` (`id_responsable` ASC) VISIBLE,
  INDEX `id_talmacen` (`id_talmacen` ASC) VISIBLE,
  INDEX `id_estado_almacen` (`id_estado_almacen` ASC) VISIBLE,
  CONSTRAINT `almacen_ibfk_1`
    FOREIGN KEY (`id_talmacen`)
    REFERENCES `uacm_db`.`tipo_almacen` (`id_talmacen`),
  CONSTRAINT `almacen_ibfk_2`
    FOREIGN KEY (`id_responsable`)
    REFERENCES `uacm_db`.`personal` (`id_personal`),
  CONSTRAINT `almacen_ibfk_3`
    FOREIGN KEY (`id_estado_almacen`)
    REFERENCES `uacm_db`.`estado_almacen` (`id_estado_almacen`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `uacm_db`.`auth_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uacm_db`.`auth_group` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `uacm_db`.`django_content_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uacm_db`.`django_content_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `app_label` VARCHAR(100) NOT NULL,
  `model` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `django_content_type_app_label_model_76bd3d3b_uniq` (`app_label` ASC, `model` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 23
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `uacm_db`.`auth_permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uacm_db`.`auth_permission` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `content_type_id` INT NOT NULL,
  `codename` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `auth_permission_content_type_id_codename_01ab375a_uniq` (`content_type_id` ASC, `codename` ASC) VISIBLE,
  CONSTRAINT `auth_permission_content_type_id_2f476e4b_fk_django_co`
    FOREIGN KEY (`content_type_id`)
    REFERENCES `uacm_db`.`django_content_type` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 89
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `uacm_db`.`auth_group_permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uacm_db`.`auth_group_permissions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `group_id` INT NOT NULL,
  `permission_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `auth_group_permissions_group_id_permission_id_0cd325b0_uniq` (`group_id` ASC, `permission_id` ASC) VISIBLE,
  INDEX `auth_group_permissio_permission_id_84c5c92e_fk_auth_perm` (`permission_id` ASC) VISIBLE,
  CONSTRAINT `auth_group_permissio_permission_id_84c5c92e_fk_auth_perm`
    FOREIGN KEY (`permission_id`)
    REFERENCES `uacm_db`.`auth_permission` (`id`),
  CONSTRAINT `auth_group_permissions_group_id_b120cbf9_fk_auth_group_id`
    FOREIGN KEY (`group_id`)
    REFERENCES `uacm_db`.`auth_group` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `uacm_db`.`auth_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uacm_db`.`auth_user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `password` VARCHAR(128) NOT NULL,
  `last_login` DATETIME(6) NULL DEFAULT NULL,
  `is_superuser` TINYINT(1) NOT NULL,
  `username` VARCHAR(150) NOT NULL,
  `first_name` VARCHAR(150) NOT NULL,
  `last_name` VARCHAR(150) NOT NULL,
  `email` VARCHAR(254) NOT NULL,
  `is_staff` TINYINT(1) NOT NULL,
  `is_active` TINYINT(1) NOT NULL,
  `date_joined` DATETIME(6) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username` (`username` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `uacm_db`.`auth_user_groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uacm_db`.`auth_user_groups` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `group_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `auth_user_groups_user_id_group_id_94350c0c_uniq` (`user_id` ASC, `group_id` ASC) VISIBLE,
  INDEX `auth_user_groups_group_id_97559544_fk_auth_group_id` (`group_id` ASC) VISIBLE,
  CONSTRAINT `auth_user_groups_group_id_97559544_fk_auth_group_id`
    FOREIGN KEY (`group_id`)
    REFERENCES `uacm_db`.`auth_group` (`id`),
  CONSTRAINT `auth_user_groups_user_id_6a12ed8b_fk_auth_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `uacm_db`.`auth_user` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `uacm_db`.`auth_user_user_permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uacm_db`.`auth_user_user_permissions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `permission_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `auth_user_user_permissions_user_id_permission_id_14a6b632_uniq` (`user_id` ASC, `permission_id` ASC) VISIBLE,
  INDEX `auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm` (`permission_id` ASC) VISIBLE,
  CONSTRAINT `auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm`
    FOREIGN KEY (`permission_id`)
    REFERENCES `uacm_db`.`auth_permission` (`id`),
  CONSTRAINT `auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `uacm_db`.`auth_user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `uacm_db`.`categoria_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uacm_db`.`categoria_producto` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `nombre_categoria` VARCHAR(100) NOT NULL,
  `descripcion_categoria` VARCHAR(300) NOT NULL,
  `id_estatus` INT NULL DEFAULT NULL,
  `fecha_creacion` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `uacm_db`.`estatus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uacm_db`.`estatus` (
  `id_estatus` INT NOT NULL AUTO_INCREMENT,
  `nombre_estatus` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_estatus`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `uacm_db`.`marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uacm_db`.`marca` (
  `id_marca` INT NOT NULL AUTO_INCREMENT,
  `nombre_marca` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_marca`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `uacm_db`.`unidad_medida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uacm_db`.`unidad_medida` (
  `id_unidad` INT NOT NULL AUTO_INCREMENT,
  `nombre_unidad` VARCHAR(50) NOT NULL,
  `abreviatura` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`id_unidad`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `uacm_db`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uacm_db`.`producto` (
  `id_producto` INT NOT NULL AUTO_INCREMENT,
  `id_estatus` INT NULL DEFAULT NULL,
  `id_categoria` INT NULL DEFAULT NULL,
  `id_marca` INT NULL DEFAULT NULL,
  `id_unidad` INT NULL DEFAULT NULL,
  `nombre_producto` VARCHAR(100) NOT NULL,
  `descripcion_producto` VARCHAR(300) NULL DEFAULT NULL,
  `cantidad` INT NOT NULL,
  `stock_minimo` INT NOT NULL,
  `observaciones` VARCHAR(300) NULL DEFAULT NULL,
  `fecha_creacion` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `imagen_producto` VARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`id_producto`),
  INDEX `id_estatus` (`id_estatus` ASC) VISIBLE,
  INDEX `id_categoria` (`id_categoria` ASC) VISIBLE,
  INDEX `id_marca` (`id_marca` ASC) VISIBLE,
  INDEX `id_unidad` (`id_unidad` ASC) VISIBLE,
  CONSTRAINT `producto_ibfk_1`
    FOREIGN KEY (`id_estatus`)
    REFERENCES `uacm_db`.`estatus` (`id_estatus`),
  CONSTRAINT `producto_ibfk_2`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `uacm_db`.`categoria_producto` (`id_categoria`),
  CONSTRAINT `producto_ibfk_3`
    FOREIGN KEY (`id_marca`)
    REFERENCES `uacm_db`.`marca` (`id_marca`),
  CONSTRAINT `producto_ibfk_4`
    FOREIGN KEY (`id_unidad`)
    REFERENCES `uacm_db`.`unidad_medida` (`id_unidad`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `uacm_db`.`estatus_solicitud`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uacm_db`.`estatus_solicitud` (
  `id_estatus_solicitud` INT NOT NULL AUTO_INCREMENT,
  `nombre_estatus` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_estatus_solicitud`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `uacm_db`.`solicitud`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uacm_db`.`solicitud` (
  `id_solicitud` INT NOT NULL AUTO_INCREMENT,
  `id_almacen` INT NULL DEFAULT NULL,
  `id_personal` INT NULL DEFAULT NULL,
  `fecha_solicitud` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `observaciones_solicitud` VARCHAR(300) NULL DEFAULT NULL,
  `id_estatus` INT NULL DEFAULT '1',
  PRIMARY KEY (`id_solicitud`),
  INDEX `id_almacen` (`id_almacen` ASC) VISIBLE,
  INDEX `id_personal` (`id_personal` ASC) VISIBLE,
  INDEX `fk_solicitud_estatus_sol` (`id_estatus` ASC) VISIBLE,
  CONSTRAINT `fk_solicitud_estatus_sol`
    FOREIGN KEY (`id_estatus`)
    REFERENCES `uacm_db`.`estatus_solicitud` (`id_estatus_solicitud`),
  CONSTRAINT `solicitud_ibfk_1`
    FOREIGN KEY (`id_almacen`)
    REFERENCES `uacm_db`.`almacen` (`id_almacen`),
  CONSTRAINT `solicitud_ibfk_2`
    FOREIGN KEY (`id_personal`)
    REFERENCES `uacm_db`.`personal` (`id_personal`))
ENGINE = InnoDB
AUTO_INCREMENT = 45
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `uacm_db`.`detalle_solicitud`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uacm_db`.`detalle_solicitud` (
  `id_detalle` INT NOT NULL AUTO_INCREMENT,
  `id_solicitud` INT NOT NULL,
  `id_producto` INT NOT NULL,
  `cantidad` INT NOT NULL,
  PRIMARY KEY (`id_detalle`),
  UNIQUE INDEX `id_solicitud` (`id_solicitud` ASC, `id_producto` ASC) VISIBLE,
  INDEX `fk_detalle_producto` (`id_producto` ASC) VISIBLE,
  CONSTRAINT `fk_detalle_producto`
    FOREIGN KEY (`id_producto`)
    REFERENCES `uacm_db`.`producto` (`id_producto`),
  CONSTRAINT `fk_detalle_solicitud`
    FOREIGN KEY (`id_solicitud`)
    REFERENCES `uacm_db`.`solicitud` (`id_solicitud`))
ENGINE = InnoDB
AUTO_INCREMENT = 73
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `uacm_db`.`django_admin_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uacm_db`.`django_admin_log` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `action_time` DATETIME(6) NOT NULL,
  `object_id` LONGTEXT NULL DEFAULT NULL,
  `object_repr` VARCHAR(200) NOT NULL,
  `action_flag` SMALLINT UNSIGNED NOT NULL,
  `change_message` LONGTEXT NOT NULL,
  `content_type_id` INT NULL DEFAULT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `django_admin_log_content_type_id_c4bce8eb_fk_django_co` (`content_type_id` ASC) VISIBLE,
  INDEX `django_admin_log_user_id_c564eba6_fk_auth_user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `django_admin_log_content_type_id_c4bce8eb_fk_django_co`
    FOREIGN KEY (`content_type_id`)
    REFERENCES `uacm_db`.`django_content_type` (`id`),
  CONSTRAINT `django_admin_log_user_id_c564eba6_fk_auth_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `uacm_db`.`auth_user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `uacm_db`.`django_migrations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uacm_db`.`django_migrations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `app` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `applied` DATETIME(6) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 20
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `uacm_db`.`django_session`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uacm_db`.`django_session` (
  `session_key` VARCHAR(40) NOT NULL,
  `session_data` LONGTEXT NOT NULL,
  `expire_date` DATETIME(6) NOT NULL,
  PRIMARY KEY (`session_key`),
  INDEX `django_session_expire_date_a5c62663` (`expire_date` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `uacm_db`.`perfil_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uacm_db`.`perfil_usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_personal` INT NULL DEFAULT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `perfil_usuario_user_id_a77a2a33_fk_auth_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `uacm_db`.`auth_user` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

USE `uacm_db` ;

-- -----------------------------------------------------
-- procedure sp_crear_solicitud
-- -----------------------------------------------------

DELIMITER $$
USE `uacm_db`$$
CREATE DEFINER=`root`@`%` PROCEDURE `sp_crear_solicitud`(
      IN p_id_almacen    INT,
      IN p_id_personal   INT,
      IN p_observaciones VARCHAR(300),
      IN p_productos     JSON
  )
BEGIN
      DECLARE v_id_solicitud INT;
      DECLARE v_index        INT DEFAULT 0;
      DECLARE v_total        INT DEFAULT 0;
      DECLARE v_id_producto  INT;
      DECLARE v_cantidad     INT;
      DECLARE v_stock        INT;

      DECLARE EXIT HANDLER FOR SQLEXCEPTION
      BEGIN
          ROLLBACK;
          SIGNAL SQLSTATE '45000'
          SET MESSAGE_TEXT = 'Error al crear la solicitud';
      END;

      START TRANSACTION;

      INSERT INTO solicitud (
          id_almacen,
          id_personal,
          observaciones_solicitud,
          id_estatus
      )
      VALUES (
          p_id_almacen,
          p_id_personal,
          p_observaciones,
          1
      );

      SET v_id_solicitud = LAST_INSERT_ID();
      SET v_total = IFNULL(JSON_LENGTH(p_productos), 0);

      WHILE v_index < v_total DO

          SET v_id_producto = CAST(
              JSON_UNQUOTE(JSON_EXTRACT(p_productos, CONCAT('$[', v_index, '].id_producto')))
          AS UNSIGNED);

          SET v_cantidad = CAST(
              JSON_UNQUOTE(JSON_EXTRACT(p_productos, CONCAT('$[', v_index, '].cantidad')))
          AS UNSIGNED);

          SELECT cantidad INTO v_stock
          FROM producto
          WHERE id_producto = v_id_producto
          FOR UPDATE;

          IF v_stock < v_cantidad THEN
              SIGNAL SQLSTATE '45000'
              SET MESSAGE_TEXT = 'Stock insuficiente';
          END IF;

          INSERT INTO detalle_solicitud (id_solicitud, id_producto, cantidad)
          VALUES (v_id_solicitud, v_id_producto, v_cantidad);

          UPDATE producto
          SET cantidad = cantidad - v_cantidad
          WHERE id_producto = v_id_producto;

          SET v_index = v_index + 1;
      END WHILE;

      COMMIT;

      SELECT
          s.id_solicitud,
          s.fecha_solicitud,
          e.nombre_estatus,
          a.id_almacen,
          ta.tipo_almacen
      FROM solicitud s
      JOIN estatus e       ON e.id_estatus   = s.id_estatus
      JOIN almacen a       ON a.id_almacen   = s.id_almacen
      JOIN tipo_almacen ta ON ta.id_talmacen = a.id_talmacen
      WHERE s.id_solicitud = v_id_solicitud;

  END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
