"""
Django settings for SistemaUACM project.

Generated by 'django-admin startproject' using Django 4.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from dotenv import load_dotenv
import environ
from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&c8@n#@t_9kl4@p23b53hrwp^&h6ritkhbrrf^2931_p(2ok+6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']  # vista pública


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'SistemaUACM',
    'Login',
    'GestiondeProductos',
    'Reportes',
    'Solicitudes'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'SistemaUACM.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'frontend_uacm/build')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'SistemaUACM.wsgi.application'


env = environ.Env()
environ.Env.read_env()  # Lee el archivo .env

# Obtener la URL de la base de datos
DATABASES = {
    'default': env.db('DATABASE_URL')  # Usa la variable DATABASE_URL del archivo .env
}



AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'es'
MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'

TIME_ZONE = 'America/Mexico_City'


USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/


STATIC_URL = '/static/'  # Ruta base para archivos estáticos
STATICFILES_DIRS = [
    # Incluye la carpeta de React
    os.path.join(BASE_DIR, 'frontend_uacm/build/static'),
]
# Carpeta donde se recopilan los archivos
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# MODIFICACIONES
LOGIN_URL = '/login/'  # Ruta para redirigir cuando el usuario no esté autenticado

CSRF_COOKIE_NAME = 'csrftoken'
# Tiempo de expiración de la sesión
# Almacenamiento en base de datos
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
# Tiempo en segundos que la sesión será válida (1 hora)
SESSION_COOKIE_AGE = 1800 # segundos
# Cierra la sesión cuando se cierre el navegador
SESSION_EXPIRE_AT_BROWSER_CLOSE = False


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR)  # ahora MEDIA_ROOT apunta al proyecto completo
