# Generated by Django 4.2.27 on 2026-03-17 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_personal', models.CharField(db_column='nombre_personal', max_length=100)),
                ('nombre_almacen', models.CharField(db_column='nombre_almacen', max_length=250)),
                ('nombre_producto', models.CharField(db_column='nombre_producto', max_length=100)),
                ('cantidad_solicitada', models.IntegerField(db_column='cantidad_solicitada')),
                ('fecha_solicitud', models.DateTimeField(db_column='fecha_solicitud')),
            ],
            options={
                'verbose_name_plural': 'Reportes de Solicitudes',
                'db_table': 'reporte_solicitud',
                'managed': False,
            },
        ),
    ]
