# Generated by Django 4.2.27 on 2026-03-17 00:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GestiondeProductos', '0001_initial'),
        ('SistemaUACM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstatusSolicitud',
            fields=[
                ('id_estatus_solicitud', models.AutoField(db_column='id_estatus_solicitud', primary_key=True, serialize=False)),
                ('nombre_estatus', models.CharField(db_column='nombre_estatus', max_length=100)),
            ],
            options={
                'db_table': 'estatus_solicitud',
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id_solicitud', models.AutoField(db_column='id_solicitud', primary_key=True, serialize=False)),
                ('fecha_solicitud', models.DateTimeField(db_column='fecha_solicitud', default=django.utils.timezone.now)),
                ('observaciones_solicitud', models.CharField(blank=True, db_column='observaciones_solicitud', max_length=300, null=True)),
                ('id_almacen', models.ForeignKey(blank=True, db_column='id_almacen', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='SistemaUACM.almacen')),
                ('id_estatus', models.ForeignKey(blank=True, db_column='id_estatus', default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Solicitudes.estatussolicitud')),
                ('id_personal', models.ForeignKey(blank=True, db_column='id_personal', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='SistemaUACM.personal')),
            ],
            options={
                'verbose_name_plural': 'Solicitudes',
                'db_table': 'solicitud',
            },
        ),
        migrations.CreateModel(
            name='DetalleSolicitud',
            fields=[
                ('id_detalle', models.AutoField(db_column='id_detalle', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(db_column='cantidad')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.DO_NOTHING, to='GestiondeProductos.producto')),
                ('id_solicitud', models.ForeignKey(db_column='id_solicitud', on_delete=django.db.models.deletion.CASCADE, to='Solicitudes.solicitud')),
            ],
            options={
                'db_table': 'detalle_solicitud',
                'unique_together': {('id_solicitud', 'id_producto')},
            },
        ),
    ]
