# Generated by Django 4.2.27 on 2026-04-03 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='aprobado_por',
            field=models.CharField(blank=True, db_column='aprobado_por', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='fecha_aprobacion',
            field=models.DateTimeField(blank=True, db_column='fecha_aprobacion', null=True),
        ),
    ]
