# Generated by Django 4.2.27 on 2026-04-03 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SistemaUACM', '0001_initial'),
        ('Solicitudes', '0002_solicitud_aprobado_por_solicitud_fecha_aprobacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='aprobado_por',
            field=models.ForeignKey(blank=True, db_column='aprobado_por', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='solicitudes_aprobadas', to='SistemaUACM.personal'),
        ),
    ]
