# Generated by Django 4.2.27 on 2026-04-03 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SistemaUACM', '0001_initial'),
        ('Solicitudes', '0005_rename_columns_in_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallesolicitud',
            name='cantidad_recibida',
            field=models.IntegerField(blank=True, db_column='cantidad_recibida', null=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_gestion',
            field=models.DateTimeField(blank=True, db_column='fecha_gestion', null=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='gestionado_por',
            field=models.ForeignKey(blank=True, db_column='gestionado_por', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='solicitudes_gestionadas', to='SistemaUACM.personal'),
        ),
    ]
