# Generated by Django 4.2.27 on 2026-03-17 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaSalarial',
            fields=[
                ('id_cat_sal', models.AutoField(db_column='id_cat_sal', primary_key=True, serialize=False)),
                ('categoria_salarial', models.CharField(db_column='categoria_salarial', max_length=50)),
                ('descripcion', models.CharField(db_column='descripcion', max_length=200)),
            ],
            options={
                'db_table': 'categoria_salarial',
            },
        ),
        migrations.CreateModel(
            name='EstadoAlmacen',
            fields=[
                ('id_estado_almacen', models.AutoField(db_column='id_estado_almacen', primary_key=True, serialize=False)),
                ('nombre_estado_almacen', models.CharField(db_column='nombre_estado_almacen', max_length=50)),
            ],
            options={
                'db_table': 'estado_almacen',
            },
        ),
        migrations.CreateModel(
            name='Estatus',
            fields=[
                ('id_estatus', models.AutoField(db_column='id_estatus', primary_key=True, serialize=False)),
                ('nombre_estatus', models.CharField(db_column='nombre_estatus', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'estatus',
                'db_table': 'estatus',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(db_column='id_rol', primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(db_column='nombre_rol', max_length=25)),
            ],
            options={
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='TipoAlmacen',
            fields=[
                ('id_talmacen', models.AutoField(db_column='id_talmacen', primary_key=True, serialize=False)),
                ('tipo_almacen', models.CharField(db_column='tipo_almacen', max_length=50)),
            ],
            options={
                'db_table': 'tipo_almacen',
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id_personal', models.IntegerField(db_column='id_personal', primary_key=True, serialize=False)),
                ('nombre_personal', models.CharField(db_column='nombre_personal', max_length=50)),
                ('apellido_paterno', models.CharField(db_column='apellido_paterno', max_length=50)),
                ('apellido_materno', models.CharField(blank=True, db_column='apellido_materno', max_length=50, null=True)),
                ('telefono', models.CharField(db_column='telefono', max_length=10)),
                ('correo', models.EmailField(db_column='correo', max_length=250)),
                ('id_categoria_sal', models.ForeignKey(blank=True, db_column='id_categoria_sal', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='SistemaUACM.categoriasalarial')),
                ('id_rol', models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.DO_NOTHING, to='SistemaUACM.rol')),
            ],
            options={
                'db_table': 'personal',
            },
        ),
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id_almacen', models.AutoField(db_column='id_almacen', primary_key=True, serialize=False)),
                ('direccion', models.CharField(db_column='direccion', max_length=250)),
                ('correo', models.EmailField(blank=True, db_column='correo', max_length=250, null=True)),
                ('telefono', models.CharField(blank=True, db_column='telefono', max_length=10, null=True)),
                ('capacidad_maxima', models.IntegerField(db_column='capacidad_maxima')),
                ('id_estado_almacen', models.ForeignKey(db_column='id_estado_almacen', on_delete=django.db.models.deletion.DO_NOTHING, to='SistemaUACM.estadoalmacen')),
                ('id_responsable', models.OneToOneField(blank=True, db_column='id_responsable', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='SistemaUACM.personal')),
                ('id_talmacen', models.ForeignKey(db_column='id_talmacen', on_delete=django.db.models.deletion.DO_NOTHING, to='SistemaUACM.tipoalmacen')),
            ],
            options={
                'db_table': 'almacen',
            },
        ),
    ]
