# Generated by Django 4.2.27 on 2026-03-17 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SistemaUACM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id_categoria', models.AutoField(db_column='id_categoria', primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(db_column='nombre_categoria', max_length=100)),
                ('descripcion_categoria', models.CharField(db_column='descripcion_categoria', max_length=300)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('id_estatus', models.ForeignKey(blank=True, db_column='id_estatus', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='SistemaUACM.estatus')),
            ],
            options={
                'verbose_name': 'Categoría de Producto',
                'verbose_name_plural': 'Categorías de Producto',
                'db_table': 'categoria_producto',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id_marca', models.AutoField(db_column='id_marca', primary_key=True, serialize=False)),
                ('nombre_marca', models.CharField(db_column='nombre_marca', max_length=100)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'db_table': 'marca',
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id_unidad', models.AutoField(db_column='id_unidad', primary_key=True, serialize=False)),
                ('nombre_unidad', models.CharField(db_column='nombre_unidad', max_length=50)),
                ('abreviatura', models.CharField(db_column='abreviatura', max_length=5)),
            ],
            options={
                'verbose_name': 'Unidad de Medida',
                'verbose_name_plural': 'Unidades de Medida',
                'db_table': 'unidad_medida',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(db_column='id_producto', primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(db_column='nombre_producto', max_length=100)),
                ('descripcion_producto', models.CharField(blank=True, db_column='descripcion_producto', max_length=300, null=True)),
                ('cantidad', models.IntegerField(db_column='cantidad')),
                ('stock_minimo', models.IntegerField(db_column='stock_minimo')),
                ('observaciones', models.CharField(blank=True, db_column='observaciones', max_length=300, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('imagen_producto', models.CharField(blank=True, db_column='imagen_producto', max_length=250, null=True)),
                ('categoria', models.ForeignKey(blank=True, db_column='id_categoria', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='GestiondeProductos.categoriaproducto')),
                ('estatus', models.ForeignKey(blank=True, db_column='id_estatus', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='SistemaUACM.estatus', verbose_name='Imagen del Producto')),
                ('marca', models.ForeignKey(blank=True, db_column='id_marca', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='GestiondeProductos.marca')),
                ('unidad', models.ForeignKey(blank=True, db_column='id_unidad', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='GestiondeProductos.unidadmedida')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'producto',
            },
        ),
    ]
