# Generated by Django 4.2.19 on 2025-02-11 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='estatus',
            fields=[
                ('id_estatus', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estatus', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='articulos',
            fields=[
                ('id_articulo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_articulo', models.CharField(max_length=250)),
                ('descripcion_articulo', models.CharField(max_length=250)),
                ('cantidad_articulo', models.IntegerField()),
                ('qr_articulo', models.CharField(max_length=250, null=True)),
                ('id_estatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestiondeProductos.estatus')),
            ],
        ),
    ]
