# Generated by Django 4.2.1 on 2025-03-02 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estatus',
            fields=[
                ('id_estatus', models.AutoField(primary_key=True, serialize=False)),
                ('nomb_estatus', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id_articulo', models.AutoField(primary_key=True, serialize=False)),
                ('nom_articulo', models.CharField(max_length=100)),
                ('desc_articulo', models.CharField(max_length=300)),
                ('cantidad', models.IntegerField()),
                ('qr_articulo', models.CharField(max_length=250)),
                ('id_estatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestiondeProductos.estatus')),
            ],
        ),
    ]
